// Code generated by protoc-gen-go.
// source: task_perf_statistics_sample.proto
// DO NOT EDIT!

package sirius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskPerfStatisticsSample struct {
	TaskId           *uint64 `protobuf:"varint,1,req,name=task_id" json:"task_id,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	Vsize            *uint64 `protobuf:"varint,3,opt,name=vsize" json:"vsize,omitempty"`
	Rsize            *uint64 `protobuf:"varint,4,opt,name=rsize" json:"rsize,omitempty"`
	SchedRun         *uint64 `protobuf:"varint,5,opt,name=sched_run" json:"sched_run,omitempty"`
	SchedWait        *uint64 `protobuf:"varint,6,opt,name=sched_wait" json:"sched_wait,omitempty"`
	Completed        *bool   `protobuf:"varint,7,opt,name=completed" json:"completed,omitempty"`
	Hostname         *string `protobuf:"bytes,8,opt,name=hostname" json:"hostname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TaskPerfStatisticsSample) Reset()                    { *m = TaskPerfStatisticsSample{} }
func (m *TaskPerfStatisticsSample) String() string            { return proto.CompactTextString(m) }
func (*TaskPerfStatisticsSample) ProtoMessage()               {}
func (*TaskPerfStatisticsSample) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

func (m *TaskPerfStatisticsSample) GetTaskId() uint64 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *TaskPerfStatisticsSample) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *TaskPerfStatisticsSample) GetVsize() uint64 {
	if m != nil && m.Vsize != nil {
		return *m.Vsize
	}
	return 0
}

func (m *TaskPerfStatisticsSample) GetRsize() uint64 {
	if m != nil && m.Rsize != nil {
		return *m.Rsize
	}
	return 0
}

func (m *TaskPerfStatisticsSample) GetSchedRun() uint64 {
	if m != nil && m.SchedRun != nil {
		return *m.SchedRun
	}
	return 0
}

func (m *TaskPerfStatisticsSample) GetSchedWait() uint64 {
	if m != nil && m.SchedWait != nil {
		return *m.SchedWait
	}
	return 0
}

func (m *TaskPerfStatisticsSample) GetCompleted() bool {
	if m != nil && m.Completed != nil {
		return *m.Completed
	}
	return false
}

func (m *TaskPerfStatisticsSample) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskPerfStatisticsSample)(nil), "sirius.TaskPerfStatisticsSample")
}

func init() { proto.RegisterFile("task_perf_statistics_sample.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8d, 0x4d, 0x6a, 0xc3, 0x30,
	0x10, 0x46, 0xb1, 0xeb, 0xdf, 0x81, 0xd2, 0x56, 0xab, 0x59, 0xba, 0x5d, 0x75, 0xd5, 0xb3, 0x14,
	0xdc, 0xbd, 0x10, 0xb6, 0x8a, 0x87, 0x44, 0x96, 0xd0, 0x8c, 0x13, 0xc8, 0x89, 0x72, 0xcc, 0x28,
	0x32, 0xc9, 0xf2, 0x3d, 0xde, 0x7c, 0x03, 0x9f, 0x62, 0xf8, 0xa0, 0x83, 0x8d, 0xff, 0x9a, 0xc5,
	0x08, 0xb1, 0xd0, 0xc4, 0x9a, 0x8d, 0x0b, 0x47, 0xfb, 0x13, 0xa2, 0x17, 0xaf, 0x1a, 0xa6, 0x48,
	0x1b, 0x7f, 0x5d, 0x0b, 0xc0, 0xbf, 0x54, 0xff, 0xa6, 0x78, 0x7c, 0xb6, 0x63, 0x4e, 0xd5, 0x1b,
	0xb4, 0x79, 0x89, 0x66, 0x2c, 0x86, 0xf2, 0xbb, 0x52, 0x1f, 0xd0, 0x0b, 0x39, 0x9b, 0x46, 0x5d,
	0xc0, 0x32, 0xab, 0x57, 0xa8, 0x4f, 0x4c, 0x17, 0x8b, 0x2f, 0x43, 0xb1, 0x63, 0xcc, 0x58, 0x65,
	0x4c, 0x07, 0x3c, 0x2d, 0x76, 0xd6, 0x71, 0x5b, 0xb1, 0xce, 0x4a, 0x01, 0xec, 0xea, 0x6c, 0x48,
	0xb0, 0x79, 0x64, 0x93, 0xbf, 0xbf, 0x14, 0x3b, 0x63, 0x9b, 0x54, 0xa7, 0xde, 0xa1, 0x5b, 0x3c,
	0xcb, 0x6a, 0x9c, 0xc5, 0x2e, 0x99, 0xfe, 0x16, 0x00, 0x00, 0xff, 0xff, 0x54, 0x34, 0x00, 0x9f,
	0xd6, 0x00, 0x00, 0x00,
}
