// Code generated by protoc-gen-go.
// source: task_final_report.proto
// DO NOT EDIT!

package sirius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskFinalReport struct {
	TaskId           *uint64  `protobuf:"varint,1,req,name=task_id" json:"task_id,omitempty"`
	StartTime        *uint64  `protobuf:"varint,2,opt,name=start_time" json:"start_time,omitempty"`
	FinishTime       *uint64  `protobuf:"varint,3,opt,name=finish_time" json:"finish_time,omitempty"`
	Instructions     *uint64  `protobuf:"varint,4,opt,name=instructions" json:"instructions,omitempty"`
	Cycles           *uint64  `protobuf:"varint,5,opt,name=cycles" json:"cycles,omitempty"`
	LlcRefs          *uint64  `protobuf:"varint,6,opt,name=llc_refs" json:"llc_refs,omitempty"`
	LlcMisses        *uint64  `protobuf:"varint,7,opt,name=llc_misses" json:"llc_misses,omitempty"`
	Runtime          *float64 `protobuf:"fixed64,8,opt,name=runtime" json:"runtime,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TaskFinalReport) Reset()                    { *m = TaskFinalReport{} }
func (m *TaskFinalReport) String() string            { return proto.CompactTextString(m) }
func (*TaskFinalReport) ProtoMessage()               {}
func (*TaskFinalReport) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *TaskFinalReport) GetTaskId() uint64 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *TaskFinalReport) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *TaskFinalReport) GetFinishTime() uint64 {
	if m != nil && m.FinishTime != nil {
		return *m.FinishTime
	}
	return 0
}

func (m *TaskFinalReport) GetInstructions() uint64 {
	if m != nil && m.Instructions != nil {
		return *m.Instructions
	}
	return 0
}

func (m *TaskFinalReport) GetCycles() uint64 {
	if m != nil && m.Cycles != nil {
		return *m.Cycles
	}
	return 0
}

func (m *TaskFinalReport) GetLlcRefs() uint64 {
	if m != nil && m.LlcRefs != nil {
		return *m.LlcRefs
	}
	return 0
}

func (m *TaskFinalReport) GetLlcMisses() uint64 {
	if m != nil && m.LlcMisses != nil {
		return *m.LlcMisses
	}
	return 0
}

func (m *TaskFinalReport) GetRuntime() float64 {
	if m != nil && m.Runtime != nil {
		return *m.Runtime
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskFinalReport)(nil), "sirius.TaskFinalReport")
}

func init() { proto.RegisterFile("task_final_report.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x24, 0xce, 0xc1, 0x6e, 0x83, 0x30,
	0x0c, 0x80, 0x61, 0x85, 0x31, 0x40, 0xde, 0x34, 0xa6, 0x6c, 0x52, 0x73, 0x44, 0x3d, 0xf5, 0xd4,
	0xc7, 0xe8, 0x03, 0x54, 0xbd, 0x23, 0x94, 0x82, 0x6a, 0x35, 0x24, 0x28, 0x36, 0x87, 0xbe, 0x51,
	0x1f, 0xb3, 0xc6, 0x3d, 0xe6, 0xd3, 0x1f, 0xdb, 0xb0, 0xe3, 0x81, 0xee, 0xfd, 0x84, 0x71, 0x08,
	0x7d, 0x1e, 0x97, 0x94, 0xf9, 0xb8, 0xe4, 0xc4, 0xc9, 0x56, 0x84, 0x19, 0x57, 0xda, 0x3f, 0x0d,
	0xb4, 0x17, 0x69, 0x4e, 0x5b, 0x72, 0xd6, 0xc2, 0xb6, 0x50, 0xeb, 0x37, 0xbc, 0x3a, 0xd3, 0x15,
	0x87, 0xd2, 0x5a, 0x00, 0xe2, 0x21, 0x73, 0xcf, 0x38, 0x8f, 0xae, 0xe8, 0x8c, 0xd8, 0x1f, 0x7c,
	0xc9, 0x58, 0xa4, 0xdb, 0x1b, 0x3f, 0x14, 0xff, 0xe1, 0x1b, 0x23, 0x71, 0x5e, 0x3d, 0x63, 0x8a,
	0xe4, 0x4a, 0xd5, 0x1f, 0xa8, 0xfc, 0xc3, 0x87, 0x91, 0xdc, 0xa7, 0xbe, 0x7f, 0xa1, 0x09, 0xc1,
	0xcb, 0x3d, 0x13, 0xb9, 0x4a, 0x45, 0x16, 0x6c, 0x32, 0x23, 0x91, 0x54, 0xb5, 0x9a, 0x5c, 0x91,
	0xd7, 0xa8, 0xc3, 0x1b, 0x01, 0xf3, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x32, 0x92, 0x30, 0xa5, 0xcc,
	0x00, 0x00, 0x00,
}
