// Code generated by protoc-gen-go.
// source: resource_vector.proto
// DO NOT EDIT!

package sirius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResourceVector struct {
	CpuCores         *float32 `protobuf:"fixed32,1,opt,name=cpu_cores,def=0" json:"cpu_cores,omitempty"`
	RamBw            *uint64  `protobuf:"varint,2,opt,name=ram_bw,def=0" json:"ram_bw,omitempty"`
	RamCap           *uint64  `protobuf:"varint,3,opt,name=ram_cap,def=0" json:"ram_cap,omitempty"`
	DiskBw           *uint64  `protobuf:"varint,4,opt,name=disk_bw,def=0" json:"disk_bw,omitempty"`
	DiskCap          *uint64  `protobuf:"varint,5,opt,name=disk_cap,def=0" json:"disk_cap,omitempty"`
	NetBw            *uint64  `protobuf:"varint,6,opt,name=net_bw,def=0" json:"net_bw,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ResourceVector) Reset()                    { *m = ResourceVector{} }
func (m *ResourceVector) String() string            { return proto.CompactTextString(m) }
func (*ResourceVector) ProtoMessage()               {}
func (*ResourceVector) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

const Default_ResourceVector_CpuCores float32 = 0
const Default_ResourceVector_RamBw uint64 = 0
const Default_ResourceVector_RamCap uint64 = 0
const Default_ResourceVector_DiskBw uint64 = 0
const Default_ResourceVector_DiskCap uint64 = 0
const Default_ResourceVector_NetBw uint64 = 0

func (m *ResourceVector) GetCpuCores() float32 {
	if m != nil && m.CpuCores != nil {
		return *m.CpuCores
	}
	return Default_ResourceVector_CpuCores
}

func (m *ResourceVector) GetRamBw() uint64 {
	if m != nil && m.RamBw != nil {
		return *m.RamBw
	}
	return Default_ResourceVector_RamBw
}

func (m *ResourceVector) GetRamCap() uint64 {
	if m != nil && m.RamCap != nil {
		return *m.RamCap
	}
	return Default_ResourceVector_RamCap
}

func (m *ResourceVector) GetDiskBw() uint64 {
	if m != nil && m.DiskBw != nil {
		return *m.DiskBw
	}
	return Default_ResourceVector_DiskBw
}

func (m *ResourceVector) GetDiskCap() uint64 {
	if m != nil && m.DiskCap != nil {
		return *m.DiskCap
	}
	return Default_ResourceVector_DiskCap
}

func (m *ResourceVector) GetNetBw() uint64 {
	if m != nil && m.NetBw != nil {
		return *m.NetBw
	}
	return Default_ResourceVector_NetBw
}

func init() {
	proto.RegisterType((*ResourceVector)(nil), "sirius.ResourceVector")
}

func init() { proto.RegisterFile("resource_vector.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4a, 0x2d, 0xce,
	0x2f, 0x2d, 0x4a, 0x4e, 0x8d, 0x2f, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2b, 0xce, 0x2c, 0xca, 0x2c, 0x2d, 0x56, 0xea, 0x64, 0xe4, 0xe2, 0x0b, 0x82,
	0xaa, 0x08, 0x03, 0x2b, 0x10, 0x12, 0xe1, 0xe2, 0x4c, 0x2e, 0x28, 0x8d, 0x4f, 0xce, 0x07, 0xea,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0xb2, 0x62, 0x34, 0x10, 0x12, 0xe4, 0x62, 0x2b, 0x4a, 0xcc,
	0x8d, 0x4f, 0x2a, 0x97, 0x60, 0x02, 0x0a, 0xb1, 0x80, 0x84, 0x84, 0xb8, 0xd8, 0x41, 0x42, 0xc9,
	0x89, 0x05, 0x12, 0xcc, 0x48, 0x62, 0x29, 0x99, 0xc5, 0xd9, 0x20, 0x75, 0x2c, 0x30, 0x31, 0x61,
	0x2e, 0x0e, 0xb0, 0x18, 0x48, 0x21, 0x2b, 0x4c, 0x10, 0x68, 0x5e, 0x5e, 0x6a, 0x09, 0x48, 0x1d,
	0x1b, 0x54, 0x08, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x4b, 0x4a, 0x1c, 0xab, 0x00, 0x00, 0x00,
}
