// Code generated by protoc-gen-go.
// source: task_instance_profile.proto
// DO NOT EDIT!

package sirius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TaskProfile struct {
	TaskId           *uint64 `protobuf:"varint,1,req,name=task_id" json:"task_id,omitempty"`
	AvgRuntime       *uint64 `protobuf:"varint,2,req,name=avg_runtime" json:"avg_runtime,omitempty"`
	MinRuntime       *uint64 `protobuf:"varint,3,opt,name=min_runtime" json:"min_runtime,omitempty"`
	MaxRuntime       *uint64 `protobuf:"varint,4,opt,name=max_runtime" json:"max_runtime,omitempty"`
	AvgVsize         *uint64 `protobuf:"varint,5,opt,name=avg_vsize" json:"avg_vsize,omitempty"`
	AvgRsize         *uint64 `protobuf:"varint,6,opt,name=avg_rsize" json:"avg_rsize,omitempty"`
	MaxVsize         *uint64 `protobuf:"varint,7,opt,name=max_vsize" json:"max_vsize,omitempty"`
	MaxRsize         *uint64 `protobuf:"varint,8,opt,name=max_rsize" json:"max_rsize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TaskProfile) Reset()                    { *m = TaskProfile{} }
func (m *TaskProfile) String() string            { return proto.CompactTextString(m) }
func (*TaskProfile) ProtoMessage()               {}
func (*TaskProfile) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *TaskProfile) GetTaskId() uint64 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *TaskProfile) GetAvgRuntime() uint64 {
	if m != nil && m.AvgRuntime != nil {
		return *m.AvgRuntime
	}
	return 0
}

func (m *TaskProfile) GetMinRuntime() uint64 {
	if m != nil && m.MinRuntime != nil {
		return *m.MinRuntime
	}
	return 0
}

func (m *TaskProfile) GetMaxRuntime() uint64 {
	if m != nil && m.MaxRuntime != nil {
		return *m.MaxRuntime
	}
	return 0
}

func (m *TaskProfile) GetAvgVsize() uint64 {
	if m != nil && m.AvgVsize != nil {
		return *m.AvgVsize
	}
	return 0
}

func (m *TaskProfile) GetAvgRsize() uint64 {
	if m != nil && m.AvgRsize != nil {
		return *m.AvgRsize
	}
	return 0
}

func (m *TaskProfile) GetMaxVsize() uint64 {
	if m != nil && m.MaxVsize != nil {
		return *m.MaxVsize
	}
	return 0
}

func (m *TaskProfile) GetMaxRsize() uint64 {
	if m != nil && m.MaxRsize != nil {
		return *m.MaxRsize
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskProfile)(nil), "sirius.TaskProfile")
}

func init() { proto.RegisterFile("task_instance_profile.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x49, 0x2c, 0xce,
	0x8e, 0xcf, 0xcc, 0x2b, 0x2e, 0x49, 0xcc, 0x4b, 0x4e, 0x8d, 0x2f, 0x28, 0xca, 0x4f, 0xcb, 0xcc,
	0x49, 0xd5, 0x03, 0xd2, 0x25, 0xf9, 0x42, 0x6c, 0xc5, 0x99, 0x45, 0x99, 0xa5, 0xc5, 0x4a, 0x2b,
	0x19, 0xb9, 0xb8, 0x43, 0x80, 0xea, 0x02, 0x20, 0xb2, 0x42, 0xfc, 0x5c, 0xec, 0x10, 0x6d, 0x29,
	0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x2c, 0x42, 0xc2, 0x5c, 0xdc, 0x89, 0x65, 0xe9, 0xf1, 0x45, 0xa5,
	0x79, 0x25, 0x99, 0xb9, 0xa9, 0x12, 0x4c, 0x30, 0xc1, 0xdc, 0xcc, 0x3c, 0xb8, 0x20, 0xb3, 0x02,
	0x23, 0x54, 0x30, 0xb1, 0x02, 0x2e, 0xc8, 0x02, 0x16, 0x14, 0xe4, 0xe2, 0x04, 0x69, 0x2f, 0x2b,
	0xce, 0xac, 0x4a, 0x95, 0x60, 0x45, 0x16, 0x2a, 0x02, 0x0b, 0xb1, 0xc1, 0x84, 0x40, 0x5a, 0x21,
	0xaa, 0xd8, 0x91, 0x85, 0x20, 0xaa, 0x38, 0x40, 0x42, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d,
	0x3a, 0x1d, 0x59, 0xd1, 0x00, 0x00, 0x00,
}
