// Code generated by protoc-gen-go.
// source: whare_map_stats.proto
// DO NOT EDIT!

package sirius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WhareMapStats struct {
	NumIdle          *uint64 `protobuf:"varint,1,req,name=num_idle,def=0" json:"num_idle,omitempty"`
	NumDevils        *uint64 `protobuf:"varint,2,req,name=num_devils,def=0" json:"num_devils,omitempty"`
	NumRabbits       *uint64 `protobuf:"varint,3,req,name=num_rabbits,def=0" json:"num_rabbits,omitempty"`
	NumSheep         *uint64 `protobuf:"varint,4,req,name=num_sheep,def=0" json:"num_sheep,omitempty"`
	NumTurtles       *uint64 `protobuf:"varint,5,req,name=num_turtles,def=0" json:"num_turtles,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WhareMapStats) Reset()                    { *m = WhareMapStats{} }
func (m *WhareMapStats) String() string            { return proto.CompactTextString(m) }
func (*WhareMapStats) ProtoMessage()               {}
func (*WhareMapStats) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

const Default_WhareMapStats_NumIdle uint64 = 0
const Default_WhareMapStats_NumDevils uint64 = 0
const Default_WhareMapStats_NumRabbits uint64 = 0
const Default_WhareMapStats_NumSheep uint64 = 0
const Default_WhareMapStats_NumTurtles uint64 = 0

func (m *WhareMapStats) GetNumIdle() uint64 {
	if m != nil && m.NumIdle != nil {
		return *m.NumIdle
	}
	return Default_WhareMapStats_NumIdle
}

func (m *WhareMapStats) GetNumDevils() uint64 {
	if m != nil && m.NumDevils != nil {
		return *m.NumDevils
	}
	return Default_WhareMapStats_NumDevils
}

func (m *WhareMapStats) GetNumRabbits() uint64 {
	if m != nil && m.NumRabbits != nil {
		return *m.NumRabbits
	}
	return Default_WhareMapStats_NumRabbits
}

func (m *WhareMapStats) GetNumSheep() uint64 {
	if m != nil && m.NumSheep != nil {
		return *m.NumSheep
	}
	return Default_WhareMapStats_NumSheep
}

func (m *WhareMapStats) GetNumTurtles() uint64 {
	if m != nil && m.NumTurtles != nil {
		return *m.NumTurtles
	}
	return Default_WhareMapStats_NumTurtles
}

func init() {
	proto.RegisterType((*WhareMapStats)(nil), "sirius.WhareMapStats")
}

func init() { proto.RegisterFile("whare_map_stats.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xcf, 0x48, 0x2c,
	0x4a, 0x8d, 0xcf, 0x4d, 0x2c, 0x88, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2b, 0xce, 0x2c, 0xca, 0x2c, 0x2d, 0x56, 0x6a, 0x64, 0xe4, 0xe2, 0x0d, 0x07,
	0xa9, 0xf0, 0x4d, 0x2c, 0x08, 0x06, 0xc9, 0x0b, 0x09, 0x73, 0x71, 0xe4, 0x95, 0xe6, 0xc6, 0x67,
	0xa6, 0xe4, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x58, 0x31, 0x1a, 0x08, 0x89, 0x72, 0x71,
	0x81, 0x04, 0x53, 0x52, 0xcb, 0x32, 0x73, 0x8a, 0x25, 0x98, 0x60, 0xc2, 0x62, 0x5c, 0xdc, 0x20,
	0xe1, 0xa2, 0xc4, 0xa4, 0xa4, 0xcc, 0x92, 0x62, 0x09, 0x66, 0x98, 0xb8, 0x08, 0x17, 0x27, 0x48,
	0xbc, 0x38, 0x23, 0x35, 0xb5, 0x40, 0x82, 0x05, 0x4d, 0x75, 0x49, 0x69, 0x51, 0x49, 0x4e, 0x6a,
	0xb1, 0x04, 0x2b, 0x54, 0x1c, 0x10, 0x00, 0x00, 0xff, 0xff, 0xed, 0x7f, 0xc1, 0x62, 0xa3, 0x00,
	0x00, 0x00,
}
